// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AvatarCompressController from "./avatar_compress_controller"
application.register("avatar-compress", AvatarCompressController)

import BaseMapController from "./base_map_controller"
application.register("base-map", BaseMapController)

import BottomSheetController from "./bottom_sheet_controller"
application.register("bottom-sheet", BottomSheetController)

import ClickableCardController from "./clickable_card_controller"
application.register("clickable-card", ClickableCardController)

import CookieConsentController from "./cookie_consent_controller"
application.register("cookie-consent", CookieConsentController)

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import DestinationSearchController from "./destination_search_controller"
application.register("destination-search", DestinationSearchController)

import DispatchController from "./dispatch_controller"
application.register("dispatch", DispatchController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ErrorController from "./error_controller"
application.register("error", ErrorController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HistoryMapController from "./history_map_controller"
application.register("history-map", HistoryMapController)

import ImageLoaderController from "./image_loader_controller"
application.register("image-loader", ImageLoaderController)

import ImageViewerController from "./image_viewer_controller"
application.register("image-viewer", ImageViewerController)

import ImagesCompressController from "./images_compress_controller"
application.register("images-compress", ImagesCompressController)

import MapController from "./map_controller"
application.register("map", MapController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PostsController from "./posts_controller"
application.register("posts", PostsController)

import ScrollResetController from "./scroll_reset_controller"
application.register("scroll-reset", ScrollResetController)

import ShareButtonController from "./share_button_controller"
application.register("share-button", ShareButtonController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import UiController from "./ui_controller"
application.register("ui", UiController)
