// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BottomSheetController from "./bottom_sheet_controller"
application.register("bottom-sheet", BottomSheetController)

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import DispatchController from "./dispatch_controller"
application.register("dispatch", DispatchController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HistoryMapController from "./history_map_controller"
application.register("history-map", HistoryMapController)

import MapController from "./map_controller"
application.register("map", MapController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import UiController from "./ui_controller"
application.register("ui", UiController)
